### ISSUE TITLE
Adding simple energy support for blocks?

### ISSUE THREAD

**Issue by Pyxrs** [Technici4n/FastTransferLib#4]
![item](https://user-images.githubusercontent.com/29241972/124289907-0f71ad80-db10-11eb-9c9c-e7d93d8dec50.PNG)
I am not skilled enough to do this myself, so if anyone could that would be great

**Comment by Technici4n** [comment]
I hope [the new `SimpleEnergyIo`](https://github.com/Technici4n/FastTransferLib/blob/fabric-item-api-api/src/main/java/dev/technici4n/fasttransferlib/api/energy/base/SimpleEnergyIo.java) suits you. I haven't tested it but it should work, otherwise please let me know!

**Comment by Pyxrs** [comment]
oh, alright!
